force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Fix Appointment</fullName>
            </value>
            <value>
                <fullName>SQL</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Convert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Segment__c</fullName>
    <label>Vertical / Segment</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pharma</fullName>
            </value>
            <value>
                <fullName>Food Service</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClientSummary_HandlerTest.cls
@IsTest(SeeAllData=true)
public class ClientSummary_HandlerTest {
    
    @isTest static void Testmy(){
        test.startTest();
        ClientSummary_Handler.mytest();
        test.stopTest();
    }
    /*
    
	@isTest
    static void testGetAllAccountCount(){
        Lead__c newLead = new Lead__c();
        newLead.Lead_Status__c = 'New';
        newLead.First_Name__c = 'Test';
        newLead.Name ='Testing';
        newLead.Company__c = 'Testing Pvt Ltd';
        newLead.Email__c = 'test@gmail.com';
        newLead.Vertical_Segment__c = 'Pharma';
        insert newLead;
        
        Account activeAcc = new Account();
        activeAcc.Name = 'Qwerty';
        activeAcc.Account_Stage__c = 'Active';
        insert activeAcc;
        
        Account newAcc = new Account();
        newAcc.Account_Stage__c = 'New';
        newAcc.Name = 'Qwerty201';
        insert newAcc;
        
        Account inActiveAcc = new Account();
        inActiveAcc.Name = 'Qwerty301';
        inActiveAcc.Account_Stage__c = 'Inactive';
        insert inActiveAcc;
        
        Test.startTest();
        //ClientSummary_Handler.ClientSummaryWrapper wrp = ClientSummary_Handler.ClientSummaryWrapper();
        ClientSummary_Handler.ClientSummaryWrapper result = ClientSummary_Handler.getAllAccountCount();
        Test.stopTest();
    }

*/
}