force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Audit_Location__c.field-meta.xml
<CustomField>
    <fullName>Audit_Location__c</fullName>
    <label>Audit Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Bengaluru</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Audit_Time__c.field-meta.xml
<CustomField>
    <fullName>Audit_Time__c</fullName>
    <label>Audit Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Audited__c.field-meta.xml
<CustomField>
    <fullName>Audited__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Audited</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Fix Appointment</fullName>
            </value>
            <value>
                <fullName>SQL</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Convert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
                <isActive>false</isActive>
                <label>Bangalore</label>
            </value>
            <value>
                <fullName>Gurgaon</fullName>
                <isActive>false</isActive>
                <label>Gurgaon</label>
            </value>
            <value>
                <fullName>Indore</fullName>
                <isActive>false</isActive>
                <label>Indore</label>
            </value>
            <value>
                <fullName>Mumbai</fullName>
                <isActive>false</isActive>
                <label>Mumbai</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Disqualify</fullName>
            </value>
            <value>
                <fullName>Audited</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Segment__c</fullName>
    <label>Vertical / Segment</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pharma</fullName>
            </value>
            <value>
                <fullName>Food Service</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadStageUpdateControllerTest.cls
@isTest
public class LeadStageUpdateControllerTest {
    
     @isTest static void Testmy(){
        test.startTest();
        LeadStageUpdateController.mytest();
        test.stopTest();
    }
    
    /*
    @isTest
    static void testUpdateStageToAudit() {
        
        Lead__c leadRecord = new Lead__c();
        leadRecord.First_Name__c = 'Anwar';
        leadRecord.Name = 'Chikle';
        leadRecord.Company__c = 'Test';
        leadRecord.Region__c = 'South';
        leadRecord.Vertical_Segment__c = 'Pharma';
        leadRecord.Email__c = 'tina.g@gmail.com';
        Insert leadRecord;
        leadRecord.Sub_Stage__c ='Audit';
        leadRecord.Lead_Status__c = 'Audit';
        leadRecord.Audited__c = true;
        Time myTime = Time.newInstance(1, 2, 3, 0);
        leadRecord.Audit_Date__c = system.today();
        leadRecord.Audit_Time__c = myTime;
        leadRecord.Audit_Location__c = 'Bengaluru';
        leadRecord.Audit_Notes__c = 'NA';
        update leadRecord;
        
        LeadStageUpdateController.updateStageToAudit(leadRecord.Id);
    }
    
    @isTest
    static void testUpdateStageToJunk() {
        Lead__c leadRecord = new Lead__c();
        leadRecord.First_Name__c = 'Anwar';
        leadRecord.Name = 'Chikle';
        leadRecord.Company__c = 'Test';
        leadRecord.Region__c = 'South';
        leadRecord.Vertical_Segment__c = 'Pharma';
        leadRecord.Email__c = 'tina.g@gmail.com';
        Insert leadRecord;
        leadRecord.Sub_Stage__c ='Audit';
        leadRecord.Lead_Status__c = 'Audit';
        leadRecord.Audited__c = true;
        Time myTime = Time.newInstance(1, 2, 3, 0);
        leadRecord.Audit_Date__c = system.today();
        leadRecord.Audit_Time__c = myTime;
        leadRecord.Audit_Location__c = 'Bengaluru';
        leadRecord.Audit_Notes__c = 'NA';
        update leadRecord;
        LeadStageUpdateController.updateStageToJunk(leadRecord.Id);
        
        
        
        
    }
    
    @isTest
    static void testFetchStakeHolderDetails() {
        Lead__c leadRecord = new Lead__c();
        leadRecord.First_Name__c = 'Anwar';
        leadRecord.Name = 'Chikle';
        leadRecord.Company__c = 'Test';
        leadRecord.Region__c = 'South';
        leadRecord.Vertical_Segment__c = 'Pharma';
        leadRecord.Email__c = 'tina.g@gmail.com';
        Insert leadRecord;
        leadRecord.Sub_Stage__c ='Audit';
        leadRecord.Lead_Status__c = 'Audit';
        leadRecord.Audited__c = true;
        Time myTime = Time.newInstance(1, 2, 3, 0);
        leadRecord.Audit_Date__c = system.today();
        leadRecord.Audit_Time__c = myTime;
        leadRecord.Audit_Location__c = 'Bengaluru';
        leadRecord.Audit_Notes__c = 'NA';
        update leadRecord;
        Stakeholder_Details__c shdRecord = new Stakeholder_Details__c(Lead__c = leadRecord.Id);
        insert shdRecord;
        
        Boolean hasStakeholderDetails = LeadStageUpdateController.fetchStakeHolderDetails(leadRecord.Id);
        
        
    }
    
    @isTest
    static void testFetchStakeHolderDetails_NoDetails() {
        Lead__c leadRecord = new Lead__c();
        leadRecord.First_Name__c = 'Anwar';
        leadRecord.Name = 'Chikle';
        leadRecord.Company__c = 'Test';
        leadRecord.Region__c = 'South';
        leadRecord.Vertical_Segment__c = 'Pharma';
        leadRecord.Email__c = 'tina.g@gmail.com';
        Insert leadRecord;
        leadRecord.Sub_Stage__c ='Audit';
        leadRecord.Lead_Status__c = 'Audit';
        leadRecord.Audited__c = true;
        Time myTime = Time.newInstance(1, 2, 3, 0);
        leadRecord.Audit_Date__c = system.today();
        leadRecord.Audit_Time__c = myTime;
        leadRecord.Audit_Location__c = 'Bengaluru';
        leadRecord.Audit_Notes__c = 'NA';
        update leadRecord;
        Boolean hasStakeholderDetails = LeadStageUpdateController.fetchStakeHolderDetails(leadRecord.Id);
    }
*/
}